### ISSUE TITLE
If AffiliateWP is not active, there is no longer a requirement admin notice

### ISSUE THREAD

**Issue by amdrew** [awesomemotive/affiliatewp-affiliate-area-shortcodes#48]
While this addon exhibits the issue, it's likely also affecting any other addon using the same activation class. I'm opening it here because I need to do some work on this addon for the WordPress.org repo and this is going to hold us back. Let's fix it in this addon first and then push it out to other addons.

## The issue:

In the following screenshot I have just activated the Affiliate Area Shortcodes addon. Note how AffiliateWP is not activated and there is no notice that tells the user that AffiliateWP must be activated. 

![image](https://user-images.githubusercontent.com/52581/210312253-a764de8f-ad98-4119-a570-62311b1b6161.png)

We used to show a message like this: 

![image](https://user-images.githubusercontent.com/52581/210311824-f13bd18a-bff9-43e3-b244-9d20659a88cb.png)

In the case of this addon, the notice worked for all versions up until `1.2` when this was added: https://github.com/awesomemotive/affiliatewp-affiliate-area-shortcodes/issues/37

Aside from the notice not displaying there are other issues:

1. There are two `AffiliateWP_Activation` classes included. See https://github.com/awesomemotive/affiliatewp-affiliate-area-shortcodes/blob/master/includes/lib/affwp/class-affiliatewp-activation.php and https://github.com/awesomemotive/affiliatewp-affiliate-area-shortcodes/blob/master/includes/class-activation.php
2. The activation code is super convoluted. No idea why it needs to have that much code.
3. There are incorrect textdomains, likely a copy/paste error when implementing on another addon. See `affiliatewp-afgf` in the codebase

This is probably only a small part of this but this conditional is preventing the banner from ever loading: https://github.com/awesomemotive/affiliatewp-affiliate-area-shortcodes/blob/master/affiliatewp-affiliate-area-shortcodes.php#L108-L112

The first conditional with `version_compare( $affwp_version, '2.7', '>=' )` is `true` for me since I have a version higher than `2.7`. Then it tries to load the `bootstrap` method but can't because it runs on the `affwp_plugins_loaded` hook. That hook is only available within AffiliateWP, which of course is not active.

To test and at least see the banner in the above screenshot, change `affwp_plugins_loaded` to `plugins_loaded`.

So what we need to do here is:

1. Get the notice working again. It should show when AffiliateWP is not active
2. Preserve any changes added which cater to the minimum requirements (you'll see these browsing through the code)
3. Simplify the activation code, remove the duplicate class, fix the text domains

After we have thoroughly tested this we need to roll this out to the other addons. It's a super broken experience when a user installs our free addons and there's zero indication of what to do next.

**Comment by darvinsilveira-am** [comment]
@amdrew 
I just pushed the fix for this issue, also:
- I refactored a little bit the Activation Class `__construct()` method simplifying a  few things;
- I removed the extra Activation class, I kept the same pattern I found on the add-ons that I recently worked on (Gravity and Ninja Forms add-ons);
- Fixed the translations functions;

The Activation class was built in a way that any Add-on can have it, so it will use the first instance found, I think that’s the reason it seems more complicated than should be, but I rewrote some parts to be more lean, but the logic stills the same, not sure if you want me to invest more time thinking in a whole new way to deal with this Activation class.

I also need to confirm, are we going to release a 1.3.1 version?

**Comment by amdrew** [comment]
@darvinsilveira-am Perfect, I will test it soon. yeah we'll do a 1.3.1 release for this. I do however need to make some changes to the banner and a few other bits and pieces so will get to that shortly after this issue is sorted.
